/* App entry: inject BALAGERE_CSS_STYLE (data bundle) + EXTRA_CSS into a
 * <style> tag, then mount <App/>. Replaces the DOM-gated bootstrap at the
 * bottom of the old app.js. */
import React from 'react';
import ReactDOM from 'react-dom/client';
import 'leaflet/dist/leaflet.css';
import { BALAGERE_CSS_STYLE } from './data.js';
import { App } from './components/App.js';

/* App-only styles on top of BALAGERE_CSS_STYLE (dark tokens stay there). */
const EXTRA_CSS = ''
  + '.map-el{position:absolute;inset:0}\n'
  + '@keyframes flipIn{from{transform:perspective(700px) rotateY(7deg);'
  + 'opacity:0}to{transform:none;opacity:1}}\n'
  + '.flip-step{animation:flipIn .28s ease both}\n'
  + '.dropzone{margin:10px 0;padding:24px;border:1px dashed var(--hair);'
  + 'border-radius:5px;text-align:center;color:var(--ink3);font-size:12.5px}\n'
  + '.dropzone.over{border-color:var(--accent);color:var(--ink)}\n'
  + '.slot{margin:10px 0;padding:10px 12px;border:1px dashed var(--hair);'
  + 'border-radius:5px}\n'
  + '.slot.over{border-color:var(--accent)}\n'
  + '.slot-label{display:flex;gap:10px;align-items:baseline;margin-bottom:6px}'
  + '\n.slot-label b{letter-spacing:.06em;font-size:11.5px}\n'
  + '.fld{display:flex;align-items:center;gap:9px;font-size:12px;'
  + 'color:var(--ink3);padding:7px 18px}\n'
  + '.fld label{letter-spacing:.08em;font-weight:600;font-size:10.5px;'
  + 'min-width:48px}\n'
  + '.fld input[type=range]{flex:1;accent-color:var(--accent)}\n'
  + '.fld .val{font-family:var(--mono);font-size:12.5px;color:var(--ink);'
  + 'min-width:52px;text-align:right;font-variant-numeric:tabular-nums}\n'
  + '.fld.files{align-items:flex-start}\n'
  + '.fld.files label{padding-top:2px}\n'
  + '.filelist{display:flex;flex-direction:column;gap:5px;min-width:0;flex:1}\n'
  + '.filerow{display:flex;align-items:baseline;gap:10px;'
  + 'justify-content:space-between}\n'
  + '.filerow b{letter-spacing:.06em;font-weight:600;font-size:11px;'
  + 'color:var(--ink3);white-space:nowrap}\n'
  + '.filelink{font-family:var(--mono);font-size:12px;color:var(--ink2);'
  + 'text-decoration:none}\n'
  + '.filelink:hover{color:var(--ink);text-decoration:underline}\n'
  + '.filelink.disabled{color:var(--ink3);opacity:.55;cursor:not-allowed}\n'
  + '.sheet .closex{position:absolute;top:10px;right:12px;min-width:0;'
  + 'padding:4px 10px}\n'
  + '.modal textarea{width:100%;background:var(--surface2);'
  + 'border:1px solid var(--hair);border-radius:3px;color:var(--ink);'
  + 'font:inherit;font-size:13px;padding:8px 10px;margin:6px 0;resize:vertical}\n'
  + '.modal input[type=file]{color:var(--ink3);font-size:12px;margin:6px 0}\n'
  + '.modal .row{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}\n'
  + '.modal button[disabled]{opacity:.45;cursor:not-allowed}\n'
  + '.reject{font-size:11.5px;color:var(--red);margin:4px 0}\n'
  + '.hint{font-size:11.5px;color:var(--ink3);margin:8px 0}\n'
  + '.review{display:grid;grid-template-columns:auto 1fr;gap:6px 14px;'
  + 'font-size:12.5px;color:var(--ink2);margin:10px 0}\n'
  + '.review b{color:var(--ink3);font-weight:600;letter-spacing:.08em;'
  + 'font-size:10px}\n'
  + '/* active-sim pins: a container-level layer so it stacks ABOVE the\n'
  + '   sim-canvas (640) — no Leaflet pane can (map-pane traps the stack) */\n'
  + '.active-pins-layer{position:absolute;inset:0;pointer-events:none}\n'
  + '.active-pins-layer .sim-pin{position:absolute;background:transparent;'
  + 'border:none;pointer-events:none}\n'
  + '.active-pins-layer .sim-pin .dot{pointer-events:auto}\n'
  + '.active-pins-layer .sim-pin .tip{display:none;position:absolute;'
  + 'bottom:calc(100% + 8px);left:50%;transform:translateX(-50%);\n'
  + '  background:var(--tag-bg);border:1px solid var(--hair-strong);\n'
  + '  color:var(--tag-ink);font-family:var(--body);font-size:11.5px;\n'
  + '  white-space:nowrap;padding:6px 10px;border-radius:var(--r-xs);\n'
  + '  box-shadow:var(--shadow-lg)}\n'
  + '.active-pins-layer .sim-pin:hover .tip{display:block}\n'
  + '.sim-canvas{position:absolute;top:0;left:0;z-index:640;pointer-events:none}\n'
  + '/* minimized anchor/rotation bar: modal-veil is gone while this shows,\n'
  + '   so the map underneath stays fully pannable / zoomable / clickable */\n'
  + '.anchor-bar{position:absolute;left:50%;bottom:22px;transform:translateX(-50%);\n'
  + '  z-index:900;display:flex;align-items:center;gap:14px;background:var(--surface);\n'
  + '  border:1px solid var(--hair);border-radius:var(--r-md);padding:10px 14px;\n'
  + '  box-shadow:var(--shadow-lg);max-width:min(720px,92%)}\n'
  + '.anchor-bar .ab-step{font-family:var(--mono);font-size:10px;\n'
  + '  letter-spacing:.14em;color:var(--ink3);white-space:nowrap}\n'
  + '.anchor-bar .ab-body{flex:1;font-size:12.5px;color:var(--ink2);\n'
  + '  min-width:180px}\n'
  + '.anchor-bar .ab-body .num{font-family:var(--mono);color:var(--ink);\n'
  + '  font-variant-numeric:tabular-nums}\n'
  + '.anchor-bar .ab-row{display:flex;gap:8px}\n'
  + '.anchor-bar button{min-width:0;padding:8px 14px}\n'
  + '.anchor-bar .fld{flex:1}\n'
  + '/* export draw mode: crosshair pinned to the map container center,\n'
  + '   above .sim-canvas (640), below .anchor-bar (900) */\n'
  + '.export-crosshair{position:absolute;left:50%;top:50%;width:0;height:0;\n'
  + '  z-index:800;pointer-events:none}\n'
  + '.export-crosshair i{position:absolute;display:block;background:var(--accent)}\n'
  + '.export-crosshair .ch{left:-10px;top:-0.75px;width:20px;height:1.5px}\n'
  + '.export-crosshair .cv{top:-10px;left:-0.75px;width:1.5px;height:20px}\n'
  + '/* loading screen: covers the map area until the first tile load */\n'
  + '.loader{position:absolute;inset:0;z-index:1200;background:var(--ground);\n'
  + '  display:flex;flex-direction:column;align-items:center;\n'
  + '  justify-content:center;gap:16px}\n'
  + '.loader .mark{font-size:15px}\n'
  + '.loader .spin{width:30px;height:30px;border-radius:50%;\n'
  + '  border:3px solid var(--hair);border-top-color:var(--accent);\n'
  + '  animation:simospin .8s linear infinite}\n'
  + '@keyframes simospin{to{transform:rotate(360deg)}}\n'
  + '.loader .msg{font-size:12.5px;color:var(--ink3);letter-spacing:.04em}\n'
  + '/* review flow: dashboard overlay + status chips + comment threads */\n'
  + '.dash-veil{position:absolute;inset:0;z-index:1000;'
  + 'background:var(--veil);display:flex;align-items:center;'
  + 'justify-content:center}\n'
  + '.dash{width:min(880px,94%);max-height:88%;overflow:auto;'
  + 'background:var(--surface);border:1px solid var(--hair);'
  + 'border-radius:var(--r-lg);padding:16px 20px;box-shadow:var(--shadow-lg)}\n'
  + '.dash-head{display:flex;align-items:center;justify-content:space-between;'
  + 'gap:10px;margin-bottom:6px}\n'
  + '.dash h3{margin:4px 0}\n'
  + '.filter{display:flex;gap:6px;align-items:center}\n'
  + '.filter button.on{border-color:var(--accent)}\n'
  + '.row-item{border:1px solid var(--hair);border-radius:var(--r-md);'
  + 'padding:10px 12px;margin:8px 0}\n'
  + '.row-line{display:flex;align-items:center;gap:10px;flex-wrap:wrap}\n'
  + '.row-title{border:0;background:none;color:var(--ink);font:inherit;'
  + 'font-weight:600;cursor:pointer;padding:0;text-align:left}\n'
  + '.row-title:hover{text-decoration:underline}\n'
  + '.row-detail{margin-top:8px}\n'
  + '.row-actions{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}\n'
  + '.row-actions button{min-width:0;padding:8px 12px}\n'
  + '.row-actions input,.replybox input{flex:1;min-width:180px;'
  + 'background:var(--surface2);border:1px solid var(--hair);'
  + 'border-radius:var(--r-sm);color:var(--ink);font:inherit;font-size:12.5px;'
  + 'padding:7px 9px}\n'
  + '.meta{display:flex;gap:16px;flex-wrap:wrap;font-size:11.5px;'
  + 'color:var(--ink3);margin:8px 0}\n'
  + '.meta b{color:var(--ink2);font-weight:600}\n'
  + '.meta-inline{font-size:11.5px;color:var(--ink3)}\n'
  + '.meta-inline b{color:var(--ink2);font-weight:600}\n'
  + '.status-chip{font-family:var(--mono);font-size:10px;'
  + 'letter-spacing:.1em;padding:3px 8px;border-radius:3px;'
  + 'border:1px solid var(--hair);color:var(--ink3);white-space:nowrap}\n'
  + '.status-chip.pending{color:var(--amber);border-color:var(--amber)}\n'
  + '.status-chip.active{color:var(--green);border-color:var(--green)}\n'
  + '.status-chip.rejected,.status-chip.failed{color:var(--red);'
  + 'border-color:var(--red)}\n'
  + '.status-chip.reviewchip{position:absolute;top:38px;right:12px}\n'
  + '.thread{display:flex;flex-direction:column;gap:6px;margin:10px 0}\n'
  + '.comment{border:1px solid var(--hair);border-radius:var(--r-sm);'
  + 'padding:7px 10px;font-size:12px}\n'
  + '.comment.admin{border-left:3px solid var(--accent)}\n'
  + '.comment .who{font-weight:600;color:var(--ink2);font-size:11.5px;'
  + 'margin-right:8px}\n'
  + '.comment .when{color:var(--ink3);font-size:10.5px}\n'
  + '.comment .body{color:var(--ink2);margin-top:3px;white-space:pre-wrap}\n'
  + '.replybox,.rejectrow{display:flex;gap:8px;margin-top:8px}\n'
  + '.replybox button,.rejectrow button{min-width:0;padding:7px 12px}\n'
  + '.rejectrow input{flex:1}\n'
  + '.replybox input{flex:1}\n'
  + 'button.danger{border-color:var(--red);color:var(--red)}\n'
  + '.supersede-picker{background:var(--surface2);border:1px solid var(--hair);'
  + 'border-radius:var(--r-sm);color:var(--ink);font:inherit;font-size:12.5px;'
  + 'padding:7px 9px;min-width:200px}\n'
  + '/* sign-in gate: Google-branded CTA — white field + brand ink overrides '
  + 'the accent-red default button */\n'
  + '.gbtn{display:flex;align-items:center;justify-content:center;gap:10px;'
  + 'width:100%;background:#fff;color:#1F1F1F;border:1px solid #747775;'
  + 'border-radius:4px;font:inherit;font-size:14px;font-weight:500;'
  + 'padding:10px 16px;min-width:0}\n'
  + '.gbtn:hover{background:#f8f9fa;filter:none}\n'
  + '/* tutorials page: 16:9 youtube-nocookie embeds inside the dash panel */\n'
  + '.yt-embed{width:100%;aspect-ratio:16/9;border:0;border-radius:var(--r-sm);'
  + 'display:block;background:#000}\n'
  /* Paper (light warm) theme — design/design-sheet.html decision. THE theme
   * swap point: replace this :root block (and the tile filter + pre-paint
   * shell in index.html) to switch themes. It sits AFTER every rule above so
   * these declarations win the cascade over the generated dark tokens in
   * BALAGERE_CSS_STYLE (public/data.js is generator-owned, never edited). */
  + ':root{--ground:#F7F1E7;--surface:#FFFDF8;--surface2:#F2E9DB;'
  + '--hair:rgba(74,55,40,.14);--hair-strong:rgba(74,55,40,.26);'
  + '--ink:#2E241C;--ink2:#5C4C3E;--ink3:#8A7A66;'
  + '--accent:#C2502E;--accent-ink:#A03F22;--accent-soft:rgba(194,80,46,.10);'
  + '--accent-dim:rgba(194,80,46,.55);--on-accent:#FFFDF8;'
  + '--green:#3E7C4F;--green-dim:#2F613C;--amber:#B8771F;--red:#BE4436;'
  + '--today:#4E6E8E;--veil:rgba(58,42,28,.45);'
  + '--tag-bg:rgba(46,36,28,.88);--tag-ink:#F7F1E7;'
  + '--shadow-lg:0 18px 44px rgba(74,55,40,.16),0 4px 14px rgba(74,55,40,.10);'
  + '--shadow-sm:0 6px 16px rgba(74,55,40,.10);'
  + '--r-xs:6px;--r-sm:10px;--r-md:14px;--r-lg:16px;'
  + '--road-core:#D9C6A6;--road-casing:#B79E7C;--draft-casing:rgba(74,55,40,.78);'
  + '--serif:"Fraunces","Iowan Old Style","Palatino Linotype",Georgia,serif;'
  + '--body:"Inter",-apple-system,"Segoe UI","Helvetica Neue",Arial,sans-serif}\n'
  + '.leaflet-tile-pane{filter:sepia(.28) saturate(.6) contrast(.93) brightness(1.03)}\n'
  + '.leaflet-control-zoom{border:1px solid var(--hair)!important;box-shadow:'
  + 'var(--shadow-sm)!important;border-radius:var(--r-sm);overflow:hidden}\n'
  + '.leaflet-control-attribution{background:var(--tag-bg);color:var(--tag-ink);'
  + 'border-radius:var(--r-xs)}\n'
  + '.leaflet-control-attribution a{color:var(--ink2)}\n'
  + '.viewtoggle button.on{color:var(--on-accent)}\n'
  + '.viewtoggle{border-radius:var(--r-sm)}\n'
  + '.sim-pin .tag{color:var(--tag-ink);background:var(--tag-bg);'
  + 'border:1px solid var(--hair-strong);border-radius:var(--r-xs)}\n'
  + '.sim-pin.active .tag{border-color:var(--accent);color:var(--tag-ink)}\n'
  + '.zone-badge span{color:var(--tag-ink);background:var(--tag-bg);'
  + 'border:1px solid var(--hair-strong);border-radius:var(--r-xs)}\n'
  + '.sheet{box-shadow:var(--shadow-lg)}\n'
  + '.sheet h2{font-family:var(--serif);font-weight:600}\n'
  + '.mark{font-family:var(--serif)}\n'
  + '.mark small{font-family:var(--mono)}\n'
  + '.modal{border-radius:var(--r-lg);box-shadow:var(--shadow-lg)}\n'
  + '.modal h3{font-family:var(--serif);font-weight:600}\n'
  + '.modal input[type=text],.modal textarea{border-radius:var(--r-sm)}\n'
  + '.modal-veil{background:var(--veil)}\n'
  + '.toast{border-radius:var(--r-sm);box-shadow:var(--shadow-lg)}\n'
  + 'button{border-radius:var(--r-sm);color:var(--on-accent)}\n'
  + '.chip{border-radius:var(--r-xs)}\n'
  + '.slot{border-radius:var(--r-md)}\n'
  + '.dropzone{border-radius:var(--r-sm)}\n'
  + '.userbox input{border-radius:var(--r-xs)}\n'
  + '.yt-embed{border-radius:var(--r-sm)}\n'
  + '.export-bbox{stroke:var(--accent);fill:var(--accent)}\n';

const __simoStyle = document.createElement('style');
__simoStyle.textContent = BALAGERE_CSS_STYLE + EXTRA_CSS;
document.head.appendChild(__simoStyle);

ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App));
