/* data.js reading helpers — port of read_data_consts/decode_stats from
 * test_mock.py.
 *
 * data.js authoring contract (byte-stable, externally generated by
 * sim/build_player.py --export-mock): every top-level definition is ONE line
 * of the form `const NAME = <valid JSON>;` so this layer can JSON-parse it.
 * The ported dev_inject.js must preserve this exact line format.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const TEST_DIR = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
export const PLAYER_ROOT = path.dirname(TEST_DIR);
export const DATA_PATH = path.join(PLAYER_ROOT, 'public', 'data.js');

export function readDataConsts(p = DATA_PATH) {
  const out = {};
  const src = fs.readFileSync(p, 'utf8');
  for (const line of src.split('\n')) {
    const m = /^const\s+([A-Z0-9_]+)\s*=\s*(.*);\s*$/.exec(line);
    if (m) out[m[1]] = JSON.parse(m[2]);
  }
  return out;
}

/* Decode a packed stats blob: nFrames x 5 u16LE rows
 * [through, moving, stopped, queued, gridlock]. */
export function decodeStats(b64, nframes) {
  const raw = Buffer.from(b64, 'base64');
  if (raw.length !== nframes * 5 * 2) {
    throw new Error(`stats blob ${raw.length} bytes != ${nframes}*5*2`);
  }
  const rows = [];
  for (let f = 0; f < nframes; f++) {
    rows.push([
      raw.readUInt16LE(f * 10),
      raw.readUInt16LE(f * 10 + 2),
      raw.readUInt16LE(f * 10 + 4),
      raw.readUInt16LE(f * 10 + 6),
      raw.readUInt16LE(f * 10 + 8),
    ]);
  }
  return rows;
}
