#!/usr/bin/env node
/* One-time migration of legacy file-baked catalog entries (plan: review
 * flow + dashboards, rollout step 3). The committed public/data.js still
 * carries dev-injected ride-along entries (e.g. fff-mtza6f9y,
 * hh-mtyood9r, uu-mtzb8gji, net-area-no-u-turn-dev) that were simulated
 * BEFORE the review flow existed: they have sims rows but no entry_json /
 * review-stream artifacts, so they cannot be previewed, deactivated, or
 * served by GET /api/catalog once data.js is regenerated.
 *
 * For every CATALOG entry that has a matching sims row this tool:
 *   1. copies the entry object into sims.entry_json,
 *   2. parses public/streams/<id>.js (JSONP) and stores the payload
 *      object under uploads/<id>/review/stream.json (bucket.js contract:
 *      payload object, NOT the wrapper),
 *   3. sets sim_ready = true.
 * The status column is left untouched (legacy rows are already 'active'
 * from the schema backfill; a pending legacy row simply becomes
 * reviewable). Entries WITHOUT a sims row are dev scratch — reported and
 * skipped (they disappear from the catalog when data.js is next
 * regenerated by the external generator; this tool never edits data.js).
 *
 *   set -a; . ./.env; set +a
 *   node tools/migrate_file_entries.js [--dry-run]
 *
 * Needs the PG* + SIMO_S3_* env (same fail-fast contract as the server).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPoolFromEnv } from '../db.js';
import { createS3FromEnv, putReviewArtifacts } from '../bucket.js';
import { readCatalog } from './dev_inject.js';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DATA_PATH = path.join(ROOT, 'public', 'data.js');
const STREAMS_DIR = path.join(ROOT, 'public', 'streams');

/* Pure: split CATALOG entries by whether a sims row exists (rowIds is a
 * Set of ids with sims rows). Migratable = entry + row; scratch = no row
 * (dev-only CLI injections — they leave with the next data.js regen). */
export function collectLegacy(catalog, rowIds) {
  const cat = Array.isArray(catalog) ? catalog : [];
  const ids = rowIds instanceof Set ? rowIds : new Set(rowIds || []);
  return {
    migrate: cat.filter((e) => e && ids.has(e.id)),
    scratch: cat.filter((e) => e && !ids.has(e.id)).map((e) => e.id),
  };
}

/* Parse streams/<id>.js into the payload object (the SAME format contract
 * as test/helpers/streamPayload.js). Throws on a bad file so the caller
 * can skip the id with a clear reason. */
export function parseStreamFile(streamsDir, id) {
  const p = path.join(streamsDir, id + '.js');
  const src = fs.readFileSync(p, 'utf8');
  const m = src
    .match(/^window\.__simoStreamCallback\('[^']+',\s*(\{.*\})\);\s*$/s);
  if (!m) {
    throw new Error('not a __simoStreamCallback payload: ' + p);
  }
  return JSON.parse(m[1]);
}

/* One legacy id -> DB entry_json + sim_ready + bucket review stream.
 * pool/bucket are the real seam objects. Returns a per-id result row for
 * the report. */
export async function migrateOne(pool, bucket, id, entry, streamsDir) {
  const stream = parseStreamFile(streamsDir, id);
  await putReviewArtifacts(bucket, id, { stream });
  const r = await pool.query(
    'update sims set entry_json = $2, sim_ready = true, updated_at = now()'
    + ' where id = $1 returning status',
    [id, JSON.stringify(entry)]);
  if (r.rowCount !== 1) throw new Error('no sims row for ' + id);
  return { id, status: r.rows[0].status, stream: true };
}

async function main() {
  const dry = process.argv.includes('--dry-run');
  const src = fs.readFileSync(DATA_PATH, 'utf8');
  const catalog = readCatalog(src);
  const pool = createPoolFromEnv();
  try {
    const rows = await pool.query('select id from sims');
    const rowIds = new Set(rows.rows.map((r) => r.id));
    const { migrate, scratch } = collectLegacy(catalog, rowIds);

    process.stdout.write('catalog entries: ' + catalog.length + '\n');
    process.stdout.write('with a sims row (migratable): '
      + migrate.map((e) => e.id).join(', ') + '\n');
    process.stdout.write('without a sims row (dev scratch, skipped): '
      + (scratch.join(', ') || '(none)') + '\n');
    if (dry) {
      process.stdout.write('dry run — nothing written\n');
      return;
    }
    const bucket = createS3FromEnv();
    for (const e of migrate) {
      try {
        const r = await migrateOne(pool, bucket, e.id, e, STREAMS_DIR);
        process.stdout.write('migrated ' + r.id + ' (status '
          + r.status + ')\n');
      } catch (err) {
        process.stdout.write('skipped ' + e.id + ': '
          + String((err && err.message) || err) + '\n');
      }
    }
  } finally {
    await pool.end();
  }
}

if (process.argv[1]
    && path.resolve(process.argv[1]) === path.resolve(
      fileURLToPath(import.meta.url))) {
  main().catch((e) => {
    process.stderr.write('migrate_file_entries failed: '
      + String((e && e.message) || e) + '\n');
    process.exit(1);
  });
}