/* App entry: inject BALAGERE_CSS_STYLE (data bundle) + EXTRA_CSS into a
 * <style> tag, then mount <App/>. Replaces the DOM-gated bootstrap at the
 * bottom of the old app.js. */
import React from 'react';
import ReactDOM from 'react-dom/client';
import 'leaflet/dist/leaflet.css';
import { BALAGERE_CSS_STYLE } from './data.js';
import { App } from './components/App.js';
import { IntroShell } from './components/IntroShell.js';

/* App-only styles on top of BALAGERE_CSS_STYLE (dark tokens stay there). */
const EXTRA_CSS = ''
  + '.map-el{position:absolute;inset:0}\n'
  /* competition countdown banner: full-width strip under the topbar */
  + '.comp-banner{flex:none;background:var(--red);color:var(--on-accent);'
  + 'text-align:center;font-size:11.5px;font-weight:600;'
  + 'letter-spacing:.04em;padding:5px 12px}\n'
  + '@keyframes flipIn{from{transform:perspective(700px) rotateY(7deg);'
  + 'opacity:0}to{transform:none;opacity:1}}\n'
  + '.flip-step{animation:flipIn .28s ease both}\n'
  + '.dropzone{margin:10px 0;padding:24px;border:1px dashed var(--hair);'
  + 'border-radius:5px;text-align:center;color:var(--ink3);font-size:12.5px}\n'
  + '.dropzone.over{border-color:var(--accent);color:var(--ink)}\n'
  + '.slot{margin:10px 0;padding:10px 12px;border:1px dashed var(--hair);'
  + 'border-radius:5px}\n'
  + '.slot.over{border-color:var(--accent)}\n'
  + '.slot-label{display:flex;gap:10px;align-items:baseline;margin-bottom:6px}'
  + '\n.slot-label b{letter-spacing:.06em;font-size:11.5px}\n'
  + '.fld{display:flex;align-items:center;gap:9px;font-size:12px;'
  + 'color:var(--ink3);padding:7px 18px}\n'
  + '.fld label{letter-spacing:.08em;font-weight:600;font-size:10.5px;'
  + 'min-width:48px}\n'
  + '.fld input[type=range]{flex:1;accent-color:var(--accent)}\n'
  + '.fld .val{font-family:var(--mono);font-size:12.5px;color:var(--ink);'
  + 'min-width:52px;text-align:right;font-variant-numeric:tabular-nums}\n'
  + '.fld.stack{flex-direction:column;align-items:stretch;gap:6px}\n'
  + '.fld.files{align-items:flex-start}\n'
  + '.fld.files label{padding-top:2px}\n'
  + '.filelist{display:flex;flex-direction:column;gap:5px;min-width:0;flex:1}\n'
  + '.filerow{display:flex;align-items:baseline;gap:10px;'
  + 'justify-content:space-between}\n'
  + '.filerow b{letter-spacing:.06em;font-weight:600;font-size:11px;'
  + 'color:var(--ink3);white-space:nowrap}\n'
  + '.filelink{font-family:var(--mono);font-size:12px;color:var(--ink2);'
  + 'text-decoration:none}\n'
  + '.filelink:hover{color:var(--ink);text-decoration:underline}\n'
  + '.filelink.disabled{color:var(--ink3);opacity:.55;cursor:not-allowed}\n'
  + '.sheet .closex{position:absolute;top:10px;right:12px;min-width:0;'
  + 'padding:4px 10px}\n'
  + '.modal textarea{width:100%;background:var(--surface2);'
  + 'border:1px solid var(--hair);border-radius:3px;color:var(--ink);'
  + 'font:inherit;font-size:13px;padding:8px 10px;margin:6px 0;resize:vertical}\n'
  + '.modal input[type=file]{color:var(--ink3);font-size:12px;margin:6px 0}\n'
  + '.modal .row{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}\n'
  + '.modal button[disabled]{opacity:.45;cursor:not-allowed}\n'
  + '.reject{font-size:11.5px;color:var(--red);margin:4px 0}\n'
  + '.hint{font-size:11.5px;color:var(--ink3);margin:8px 0}\n'
  + '.review{display:grid;grid-template-columns:auto 1fr;gap:6px 14px;'
  + 'font-size:12.5px;color:var(--ink2);margin:10px 0}\n'
  + '.review b{color:var(--ink3);font-weight:600;letter-spacing:.08em;'
  + 'font-size:10px}\n'
  + '/* active-sim pins: a container-level layer so it stacks ABOVE the\n'
  + '   sim-canvas (640) — no Leaflet pane can (map-pane traps the stack) */\n'
  + '.active-pins-layer{position:absolute;inset:0;pointer-events:none}\n'
  + '.active-pins-layer .sim-pin{position:absolute;background:transparent;'
  + 'border:none;pointer-events:none}\n'
  + '.active-pins-layer .sim-pin .dot{pointer-events:auto}\n'
  + '.active-pins-layer .sim-pin .tip{display:none;position:absolute;'
  + 'bottom:calc(100% + 8px);left:50%;transform:translateX(-50%);\n'
  + '  background:var(--tag-bg);border:1px solid var(--hair-strong);\n'
  + '  color:var(--tag-ink);font-family:var(--body);font-size:11.5px;\n'
  + '  white-space:nowrap;padding:6px 10px;border-radius:var(--r-xs);\n'
  + '  box-shadow:var(--shadow-lg)}\n'
  + '.active-pins-layer .sim-pin:hover .tip{display:block}\n'
  + '/* overlapping pins spread into a vertical list on the map itself\n'
  + '   (the ActivePins layer re-lays them every sync) — no chooser\n'
  + '   popup CSS exists; the single-pin hover tip stays below */\n'
  + '.sim-canvas{position:absolute;top:0;left:0;z-index:640;pointer-events:none}\n'
  + '/* minimized anchor/rotation bar: modal-veil is gone while this shows,\n'
  + '   so the map underneath stays fully pannable / zoomable / clickable */\n'
  + '.anchor-bar{position:absolute;left:50%;bottom:22px;transform:translateX(-50%);\n'
  + '  z-index:900;display:flex;align-items:center;gap:14px;background:var(--surface);\n'
  + '  border:1px solid var(--hair);border-radius:var(--r-md);padding:10px 14px;\n'
  + '  box-shadow:var(--shadow-lg);max-width:min(720px,92%)}\n'
  + '.anchor-bar .ab-step{font-family:var(--mono);font-size:10px;\n'
  + '  letter-spacing:.14em;color:var(--ink3);white-space:nowrap}\n'
  + '.anchor-bar .ab-body{flex:1;font-size:12.5px;color:var(--ink2);\n'
  + '  min-width:180px}\n'
  + '.anchor-bar .ab-body .num{font-family:var(--mono);color:var(--ink);\n'
  + '  font-variant-numeric:tabular-nums}\n'
  + '.anchor-bar .ab-row{display:flex;gap:8px}\n'
  + '.anchor-bar button{min-width:0;padding:8px 14px}\n'
  + '.anchor-bar .fld{flex:1}\n'
  + '/* export draw mode: crosshair pinned to the map container center,\n'
  + '   above .sim-canvas (640), below .anchor-bar (900) */\n'
  + '.export-crosshair{position:absolute;left:50%;top:50%;width:0;height:0;\n'
  + '  z-index:800;pointer-events:none}\n'
  + '.export-crosshair i{position:absolute;display:block;background:var(--accent)}\n'
  + '.export-crosshair .ch{left:-10px;top:-0.75px;width:20px;height:1.5px}\n'
  + '.export-crosshair .cv{top:-10px;left:-0.75px;width:1.5px;height:20px}\n'
  + '/* loading screen: covers the map area until the first tile load */\n'
  + '.loader{position:absolute;inset:0;z-index:1200;background:var(--ground);\n'
  + '  display:flex;flex-direction:column;align-items:center;\n'
  + '  justify-content:center;gap:16px}\n'
  + '.loader .mark{font-size:15px}\n'
  + '.loader .spin{width:30px;height:30px;border-radius:50%;\n'
  + '  border:3px solid var(--hair);border-top-color:var(--accent);\n'
  + '  animation:simospin .8s linear infinite}\n'
  + '@keyframes simospin{to{transform:rotate(360deg)}}\n'
  + '.loader .msg{font-size:12.5px;color:var(--ink3);letter-spacing:.04em}\n'
  + '/* review flow: dashboard overlay + status chips + comment threads */\n'
  + '.dash-veil{position:absolute;inset:0;z-index:1000;'
  + 'background:var(--veil);display:flex;align-items:center;'
  + 'justify-content:center}\n'
  + '.dash{width:min(880px,94%);max-height:88%;overflow:auto;'
  + 'background:var(--surface);border:1px solid var(--hair);'
  + 'border-radius:var(--r-lg);padding:16px 20px;box-shadow:var(--shadow-lg)}\n'
  + '.dash-head{display:flex;align-items:center;justify-content:space-between;'
  + 'gap:10px;margin-bottom:6px}\n'
  + '.dash h3{margin:4px 0}\n'
  + '.filter{display:flex;gap:6px;align-items:center}\n'
  + '.filter button.on{border-color:var(--accent)}\n'
  + '.row-item{border:1px solid var(--hair);border-radius:var(--r-md);'
  + 'padding:10px 12px;margin:8px 0}\n'
  + '.row-line{display:flex;align-items:center;gap:10px;flex-wrap:wrap}\n'
  + 'button.row-title{border:0;background:none;color:var(--ink);font:inherit;'
  + 'font-weight:600;cursor:pointer;padding:0 0 0 4px;text-align:left}\n'
  + 'button.row-title:hover{outline:none;text-decoration:underline}\n'
  + '.row-detail{margin-top:8px}\n'
  + '.row-actions{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}\n'
  + '.row-actions button{min-width:0;padding:8px 12px}\n'
  + '.row-actions .linkbtn{border:0;background:none;color:var(--red);'
  + 'font:inherit;font-size:12.5px;font-weight:600;cursor:pointer;'
  + 'padding:0;text-align:left}\n'
  + '.row-actions .linkbtn:hover{outline:none;text-decoration:underline}\n'
  + '.row-actions input,.replybox input{flex:1;min-width:180px;'
  + 'background:var(--surface2);border:1px solid var(--hair);'
  + 'border-radius:var(--r-sm);color:var(--ink);font:inherit;font-size:12.5px;'
  + 'padding:7px 9px}\n'
  + '.meta{display:flex;gap:16px;flex-wrap:wrap;font-size:11.5px;'
  + 'color:var(--ink3);margin:8px 0}\n'
  + '.meta b{color:var(--ink2);font-weight:600}\n'
  + '.meta-inline{font-size:11.5px;color:var(--ink3)}\n'
  + '.meta-inline b{color:var(--ink2);font-weight:600}\n'
  + '.status-chip{font-family:var(--mono);font-size:10px;'
  + 'letter-spacing:.1em;padding:3px 8px;border-radius:3px;'
  + 'border:1px solid var(--hair);color:var(--ink3);white-space:nowrap}\n'
  + '.status-chip.pending{color:var(--amber);border-color:var(--amber)}\n'
  + '.status-chip.active{color:var(--green);border-color:var(--green)}\n'
  + '.status-chip.rejected,.status-chip.failed{color:var(--red);'
  + 'border-color:var(--red)}\n'
  + '.status-chip.reviewchip{margin:0 18px 10px;align-self:flex-start}\n'
  + '.thread{display:flex;flex-direction:column;gap:6px;margin:10px 0}\n'
  + '.comment{border:1px solid var(--hair);border-radius:var(--r-sm);'
  + 'padding:7px 10px;font-size:12px}\n'
  + '.comment.admin{border-left:3px solid var(--accent)}\n'
  + '.comment .who{font-weight:600;color:var(--ink2);font-size:11.5px;'
  + 'margin-right:8px}\n'
  + '.comment .when{color:var(--ink3);font-size:10.5px}\n'
  + '.comment .body{color:var(--ink2);margin-top:3px;white-space:pre-wrap}\n'
  + '.replybox,.rejectrow{display:flex;gap:8px;margin-top:8px}\n'
  + '.replybox button,.rejectrow button{min-width:0;padding:7px 12px}\n'
  + '.rejectrow input{flex:1}\n'
  + '.replybox input{flex:1}\n'
  + 'button.danger{border-color:var(--red);color:var(--red)}\n'
  + '.supersede-picker{background:var(--surface2);border:1px solid var(--hair);'
  + 'border-radius:var(--r-sm);color:var(--ink);font:inherit;font-size:12.5px;'
  + 'padding:7px 9px;min-width:200px}\n'
  + '/* sign-in gate: Google-branded CTA — white field + brand ink overrides '
  + 'the accent-red default button */\n'
  + '.gbtn{display:flex;align-items:center;justify-content:center;gap:10px;'
  + 'width:100%;background:#fff;color:#1F1F1F;border:1px solid #747775;'
  + 'border-radius:4px;font:inherit;font-size:14px;font-weight:500;'
  + 'padding:10px 16px;min-width:0}\n'
  + '.gbtn:hover{background:#f8f9fa;filter:none}\n'
  + '/* tutorials page: 16:9 youtube-nocookie embeds inside the dash panel */\n'
  + '.yt-embed{width:100%;aspect-ratio:16/9;border:0;border-radius:var(--r-sm);'
  + 'display:block;background:#000}\n'
  /* Paper (light warm) theme — design/design-sheet.html decision. THE theme
   * swap point: replace this :root block (and the tile filter + pre-paint
   * shell in index.html) to switch themes. It sits AFTER every rule above so
   * these declarations win the cascade over the generated dark tokens in
   * BALAGERE_CSS_STYLE (public/data.js is generator-owned, never edited). */
  + ':root{--ground:#F7F1E7;--surface:#FFFDF8;--surface2:#F2E9DB;'
  + '--hair:rgba(74,55,40,.14);--hair-strong:rgba(74,55,40,.26);'
  + '--ink:#2E241C;--ink2:#5C4C3E;--ink3:#8A7A66;'
  + '--accent:#C2502E;--accent-ink:#A03F22;--accent-soft:rgba(194,80,46,.10);'
  + '--accent-dim:rgba(194,80,46,.55);--on-accent:#FFFDF8;'
  + '--green:#3E7C4F;--green-dim:#2F613C;--amber:#B8771F;--red:#BE4436;'
  + '--today:#4E6E8E;--veil:rgba(58,42,28,.45);'
  + '--tag-bg:rgba(46,36,28,.88);--tag-ink:#F7F1E7;'
  + '--shadow-lg:0 18px 44px rgba(74,55,40,.16),0 4px 14px rgba(74,55,40,.10);'
  + '--shadow-sm:0 6px 16px rgba(74,55,40,.10);'
  + '--r-xs:6px;--r-sm:10px;--r-md:14px;--r-lg:16px;'
  + '--road-core:#D9C6A6;--road-casing:#B79E7C;--draft-casing:rgba(74,55,40,.78);'
  + '--serif:"Fraunces","Iowan Old Style","Palatino Linotype",Georgia,serif;'
  + '--body:"Inter",-apple-system,"Segoe UI","Helvetica Neue",Arial,sans-serif}\n'
  + '.leaflet-tile-pane{filter:sepia(.28) saturate(.6) contrast(.93) brightness(1.03)}\n'
  + '.leaflet-control-zoom{border:1px solid var(--hair)!important;box-shadow:'
  + 'var(--shadow-sm)!important;border-radius:var(--r-sm);overflow:hidden}\n'
  + '.leaflet-control-attribution{background:var(--tag-bg);color:var(--tag-ink);'
  + 'border-radius:var(--r-xs)}\n'
  + '.leaflet-control-attribution a{color:var(--ink2)}\n'
  + '.viewtoggle button.on{color:var(--on-accent)}\n'
  + '.viewtoggle{border-radius:var(--r-sm)}\n'
  + '.sim-pin .tag{color:var(--tag-ink);background:var(--tag-bg);'
  + 'border:1px solid var(--hair-strong);border-radius:var(--r-xs)}\n'
  + '.sim-pin.active .tag{border-color:var(--accent);color:var(--tag-ink)}\n'
  + '.zone-badge span{color:var(--tag-ink);background:var(--tag-bg);'
  + 'border:1px solid var(--hair-strong);border-radius:var(--r-xs)}\n'
  + '.sheet{box-shadow:var(--shadow-lg)}\n'
  + '.sheet h2{font-family:var(--serif);font-weight:700}\n'
  + '.sheet-grip{display:none}\n'
  + '.sheet-body{display:flex;flex-direction:column;flex:1;min-height:0}\n'
  + '.mark{font-family:var(--serif);font-weight:700}\n'
  + '.mark small{font-family:var(--mono)}\n'
  + '.modal{border-radius:var(--r-lg);box-shadow:var(--shadow-lg)}\n'
  + '.modal h3{font-family:var(--serif);font-weight:700}\n'
  + '.modal input[type=text],.modal textarea{border-radius:var(--r-sm)}\n'
  + '.modal-veil{background:var(--veil)}\n'
  + '.toast{border-radius:var(--r-sm);box-shadow:var(--shadow-lg)}\n'
  + 'button{border-radius:var(--r-sm);color:var(--on-accent);'
  + 'font-family:var(--body)}\n'
  /* hover language: every button keeps its surface color on hover — the
   * generated button:hover{filter:brightness(1.14)} white-outs the warm
   * Paper surfaces — and gets an accent-red ring instead. outline at -1px
   * hugs the edge like a border with zero layout shift and works on
   * border:0 controls too. The Google CTA is a brand element and keeps
   * its designed field (no ring). */
  + 'button:hover{filter:none;outline:1px solid var(--accent);'
  + 'outline-offset:-1px}\n'
  + '.gbtn:hover{outline:none}\n'
  + '.chip{border-radius:var(--r-xs)}\n'
  + '.slot{border-radius:var(--r-md)}\n'
  + '.dropzone{border-radius:var(--r-sm)}\n'
  + '.userbox input{border-radius:var(--r-xs)}\n'
  + '.yt-embed{border-radius:var(--r-sm)}\n'
  + '.export-bbox{stroke:var(--accent);fill:var(--accent)}\n'
  /* Top bar redesign (plan: Figma-style pill + More) — overrides the
   * generated .viewtoggle segmented control by cascade order (same
   * selectors, later in the sheet); token-only colors. overflow:visible so
   * the raised thumb shadow and the dropdown panels are not clipped. */
  + '.viewtoggle{overflow:visible;gap:2px;padding:3px;border-radius:999px;'
  + 'background:var(--surface2);border:1px solid var(--hair)}\n'
  + '.viewtoggle button{display:inline-flex;align-items:center;gap:5px;'
  + 'border-radius:999px;padding:6px 13px;font-size:12px;'
  + 'font-weight:500;color:var(--ink2);background:transparent;'
  + 'box-shadow:none}\n'
  + '.chev{width:10px;height:10px;flex:none}\n'
  + '.viewtoggle button:hover{color:var(--ink)}\n'
  + '.viewtoggle button.on{background:var(--surface);color:var(--ink);'
  + 'font-weight:600;box-shadow:var(--shadow-sm)}\n'
  + '.menu-wrap{position:relative;display:inline-block}\n'
  + '.more-menu{position:absolute;left:0;top:calc(100% + 8px);'
  + 'min-width:170px;background:var(--surface);border:1px solid var(--hair);'
  + 'border-radius:var(--r-md);box-shadow:var(--shadow-lg);padding:6px;'
  + 'z-index:700}\n'
  + '.more-menu button{display:block;width:100%;text-align:left;min-width:0;'
  + 'border:0;background:transparent;color:var(--ink2);font-size:12.5px;'
  + 'font-weight:500;padding:8px 11px;border-radius:var(--r-sm)}\n'
  + '.more-menu button:hover{background:var(--surface2);color:var(--ink)}\n'
  + '.avatar{display:inline-flex;align-items:center;gap:8px;'
  + 'background:transparent;border:1px solid var(--hair-strong);'
  + 'border-radius:999px;padding:3px 10px 3px 3px;color:var(--ink2);'
  + 'font-size:12.5px;font-weight:600;min-width:0}\n'
  + '.avatar:hover{border-color:var(--ink3);color:var(--ink)}\n'
  + '.avatar .ph{width:24px;height:24px;border-radius:50%;'
  + 'background:var(--accent-soft);color:var(--accent-ink);'
  + 'display:flex;align-items:center;justify-content:center;'
  + 'font-family:var(--serif);font-weight:700;font-size:12px;flex:none}\n'
  + '.account-menu{position:absolute;right:0;top:calc(100% + 8px);'
  + 'min-width:210px;background:var(--surface);border:1px solid var(--hair);'
  + 'border-radius:var(--r-md);box-shadow:var(--shadow-lg);padding:6px;'
  + 'z-index:700}\n'
  + '.account-menu .who{padding:8px 11px;font-size:10.5px;color:var(--ink3);'
  + 'font-family:var(--mono);letter-spacing:.05em}\n'
  + '.account-menu button{display:block;width:100%;text-align:left;'
  + 'min-width:0;border:0;background:transparent;color:var(--red);'
  + 'font-size:12.5px;font-weight:500;padding:8px 11px;'
  + 'border-radius:var(--r-sm)}\n'
  + '.account-menu button:hover{background:var(--surface2)}\n'
  + '/* brand + actions take equal flex so the pill stays centered in every\n'
  + '   auth state; the tagline stacks on a second line under the name and\n'
  + '   is never hidden (user decision — replaces the hide-on-narrow rule).\n'
  + '   serif/mono are re-declared: these are the last .mark rules, so the\n'
  + '   theme pins read them here. */\n'
  + '.mark{flex:1 1 0;flex-wrap:wrap;row-gap:1px;'
  + 'font-family:var(--serif);font-weight:700}\n'
  + '.mark small{display:block;flex-basis:100%;font-family:var(--mono)}\n'
  + '.userbox{flex:1 1 0;justify-content:flex-end}\n'
  /* open-source repo chip: on the brand mark's title row (the stacked
   * tagline wraps below it) — hair border, full round, token ink; hover
   * parity with the buttons (ink text + accent ring, no filter). Same 30×30
   * size as the original right-cluster chip, 15px octicon. */
  + '.mark a.gh{display:inline-flex;align-items:center;justify-content:'
   + 'center;width:30px;height:30px;flex:none;border:1px solid var(--hair);'
   + 'border-radius:999px;background:transparent;color:var(--ink2);'
   + 'text-decoration:none}\n'
   + '.mark a.gh svg{width:15px;height:15px;display:block}\n'
   + '.mark a.gh:hover{color:var(--ink);outline:1px solid var(--accent);'
   + 'outline-offset:-1px}\n'
  + '/* responsive component: compact single row <=900px; below that the\n'
  + '   bar stacks to three centered rows (brand / pill / actions).\n'
  + '   Layout-only — nothing is ever hidden. Media rules that restyle the\n'
  + '   pinned base selectors use a :where(*) tail on purpose: it keeps\n'
  + '   specificity and cascade position identical, but the selector no\n'
  + '   longer ENDS with .mark/.viewtoggle/.userbox, so the contract tests\n'
  + '   (which read the last rule per selector tail) keep reading the base\n'
  + '   layout rules, not these narrow-screen deltas. */\n'
  + '@media (max-width:900px){.topbar{padding:8px 12px;gap:10px}\n'
  + '.mark:where(*){font-size:13px}\n'
  + '.mark i{height:16px}\n'
  + '.viewtoggle:where(*){padding:2px}\n'
  + '.viewtoggle button:where(*){padding:5px 10px;font-size:11.5px}\n'
  + '.userbox:where(*){gap:6px}\n'
  + '.userbox > button{min-width:0;padding:7px 10px;font-size:12px}}\n'
  + '@media (max-width:640px){.topbar{flex-wrap:wrap;row-gap:8px;'
  + 'justify-content:center}\n'
  + '.topbar>:where(.mark,.userbox){flex:0 0 100%;justify-content:center}\n'
  + '.mark small:where(*){text-align:center}\n'
  + '.viewtoggle:where(*){flex:0 0 100%;justify-content:center}\n'
  + '.userbox:where(*){gap:4px}\n'
  + '.userbox > button{padding:7px 8px;font-size:11.5px}}\n'
  /* Intro gate (once per lifecycle). .app-reveal wraps the whole app at
   * the mount point — it replicates the #root column flex so TopBar and
   * .map-wrap keep their layout; the site stays clipped at circle(0%)
   * until IntroShell opens the reveal, and the clip is dropped entirely
   * once settled. Intro overlay: two 50% halves, each clipping a
   * full-viewport pane — the panes tile the design seamlessly and slide
   * apart along the center split on the CTA, while the site blooms open
   * from the center through the widening gap. All chrome is token-only
   * (theme-swappable); no bare button rules (theme contract). */
  + '.app-reveal{position:relative;height:100%;display:flex;flex-direction:column;'
  + 'clip-path:circle(0% at 50% 50%);transition:clip-path 1.1s cubic-bezier(.16,1,.3,1)}\n'
  + '.app-reveal.open{clip-path:circle(120% at 50% 50%)}\n'
  + '.app-reveal.settled{clip-path:none;transition:none}\n'
  + '.intro-root{position:fixed;inset:0;z-index:2000;display:flex}\n'
  + '.intro-root.intro-out{pointer-events:none}\n'
  + '.intro-half{position:relative;width:50%;height:100%;overflow:hidden;'
  + 'transition:transform .9s cubic-bezier(.16,1,.3,1)}\n'
  + '.intro-half-l .intro-pane{left:0}\n'
  + '.intro-half-r .intro-pane{left:-100%}\n'
  + '.intro-pane{position:absolute;top:0;width:200%;height:100%;'
  + 'background:var(--ground);display:flex;flex-direction:column;'
  + 'align-items:center;justify-content:center;text-align:center;padding:48px 24px}\n'
  + '.intro-out .intro-half-l{transform:translateX(-101%)}\n'
  + '.intro-out .intro-half-r{transform:translateX(101%)}\n'
  + '.intro-net{position:absolute;inset:0;width:100%;height:100%}\n'
  + '.intro-copy{position:relative;display:flex;flex-direction:column;'
  + 'align-items:center;gap:26px}\n'
  + '.intro-brand{font-family:var(--serif);font-weight:700;color:var(--ink);'
  + 'font-size:clamp(22px,3.4vw,34px);letter-spacing:-.01em}\n'
  + '.intro-tag{font-family:var(--mono);font-size:11px;letter-spacing:.16em;'
  + 'text-transform:uppercase;color:var(--accent);'
  + 'border:1px solid var(--accent-dim);background:var(--accent-soft);'
  + 'border-radius:999px;padding:5px 14px}\n'
  + '.intro-headline{font-family:var(--serif);font-weight:700;line-height:1.02;'
  + 'letter-spacing:-.02em;color:var(--ink);font-size:clamp(44px,9vw,110px)}\n'
  + '.intro-sub{font-family:var(--body);font-size:15px;color:var(--ink2);'
  + 'max-width:34em}\n'
  + '.intro-cta{display:inline-flex;align-items:center;gap:10px;'
  + 'background:var(--accent);color:var(--on-accent);border:0;cursor:pointer;'
  + 'font-family:var(--body);font-size:12.5px;font-weight:600;'
  + 'letter-spacing:.14em;text-transform:uppercase;padding:14px 30px;'
  + 'border-radius:999px;box-shadow:var(--shadow-lg);'
  + 'transition:transform .3s cubic-bezier(.16,1,.3,1),'
  + 'background .3s cubic-bezier(.16,1,.3,1)}\n'
  + '.intro-cta .arr{display:inline-flex;'
  + 'transition:transform .3s cubic-bezier(.16,1,.3,1)}\n'
  + '.intro-root.intro-hover .intro-cta{background:var(--accent-ink);'
  + 'transform:translateY(-2px)}\n'
  + '.intro-root.intro-hover .intro-cta .arr{transform:translateX(5px)}\n'
  /* the pill straddles the split (two clipped copies, one per half): a
     :hover/:focus SUBJECT would light only the copy under the pointer, so
     the state anchors on the shared root via :has() — one style recalc
     paints BOTH copies together. The .intro-hover class above stays as
     the keyboard-focus path for engines without :has(). */
  + '.intro-root:has(.intro-cta:hover) .intro-cta{background:var(--accent-ink);'
  + 'transform:translateY(-2px)}\n'
  + '.intro-root:has(.intro-cta:hover) .intro-cta .arr{transform:translateX(5px)}\n'
  + '.intro-root:has(.intro-cta:focus) .intro-cta{background:var(--accent-ink);'
  + 'transform:translateY(-2px)}\n'
  + '.intro-root:has(.intro-cta:focus) .intro-cta .arr{transform:translateX(5px)}\n'
  + '.intro-micro{font-family:var(--mono);font-size:10px;letter-spacing:.14em;'
  + 'text-transform:uppercase;color:var(--ink3)}\n'
  + '.intro-micro-top{position:absolute;top:28px;left:50%;'
  + 'transform:translateX(-50%);display:flex;gap:18px;white-space:nowrap}\n'
  + '.intro-micro-bottom{position:absolute;bottom:28px;left:50%;'
  + 'transform:translateX(-50%);white-space:nowrap}\n'
  + '@media (prefers-reduced-motion:reduce){.app-reveal,.intro-half,'
  + '.intro-cta,.intro-cta .arr{transition:none}}\n'
  /* SimPanel bottom sheet (<=900px, same breakpoint as the compact topbar):
   * the generated .sheet is a 360px right-side panel inside .map-wrap — on
   * phones it becomes a bottom sheet capped at 62% that collapses to a
   * 56px title strip (grip + h2 + ✕) while the sim runs. The strip stays
   * OUTSIDE the scroll: only .sheet-body scrolls, so the grip/h2/✕ are
   * always visible; minimized, the sheet gets touch-action:none (nothing
   * scrolls) and the pointer handlers own swipe-to-expand. Mobile order
   * puts Run on top, then the sliders, then the numbers, then FILES.
   * Media rules restyling the pinned base selectors use the :where(*) tail
   * (see the topbar block above): identical cascade weight, but the
   * selector no longer ENDS with .sheet, so the theme contract keeps
   * reading the base shadow rule. touch-action stays OFF .sheet itself —
   * an ancestor none would kill the body's touch scrolling. */
  + '@media (max-width:900px){\n'
  + '.sheet:where(*){top:auto;left:0;right:0;bottom:0;width:auto;height:auto;'
  + 'max-height:62%;border-left:0;'
  + 'border-top:1px solid var(--hair);'
  + 'border-radius:var(--r-lg) var(--r-lg) 0 0;'
  + 'transition:transform .3s cubic-bezier(.16,1,.3,1)}\n'
  + '.sheet .sheet-body:where(*){overflow-y:auto;overscroll-behavior:contain}\n'
  + '.sheet.sheet-collapsed:where(*){transform:translateY(calc(100% - 56px));'
  + 'touch-action:none}\n'
  + '.sheet.sheet-drag:where(*){transition:none;user-select:none}\n'
  + '.sheet .sheet-grip:where(*){display:block;width:34px;height:4px;'
  + 'border-radius:999px;background:var(--hair-strong);margin:8px auto 2px;'
  + 'flex:none;touch-action:none}\n'
  + '.sheet h2:where(*){touch-action:none}\n'
  + '.sheet .actions:where(*){order:-6;margin-top:0}\n'
  + '.sheet .fld:where(*){order:-5}\n'
  + '.sheet .statgrid:where(*){order:-4}\n'
  + '.sheet .scen-toggle:where(*){order:-3}\n'
+ '.sheet .fld.files:where(*){order:1}\n'
   + '.map-wrap{overflow:hidden}}\n'
   /* Capture page redesign (design reference: phone shell + dropzone +
    * accordion guide cards + ranked leaderboard rows + sign-in bottom
    * sheet). The dash panel becomes the shell: header strip and scroll
    * body are flex siblings, only .capture-body scrolls (the sticky CTA
    * bar is gone — the dropzone is the single entry point; an accepted
    * upload swaps the whole body for the success moment, then
    * auto-advances to the Leaderboard tab). Single column at EVERY
    * width; on mobile the sections split into Upload | Leaderboard tabs
    * (see the mobile block below), desktop keeps the stacked shell; 44px+
    * tap targets; token-only colors per the theme contract. */
   + '/* capture page */\n'
   + '.capture-dash{position:relative;width:min(480px,94%);'
   + 'max-height:min(780px,92%);padding:0;display:flex;'
   + 'flex-direction:column;overflow:hidden;box-shadow:var(--shadow-lg)}\n'
   + '.capture-head{margin:0;flex:none;padding:12px 16px;'
   + 'border-bottom:1px solid var(--hair)}\n'
   + '.capture-brand{width:34px;height:34px;flex:none;border-radius:var(--r-sm);'
   + 'background:var(--accent);color:var(--on-accent);display:flex;'
   + 'align-items:center;justify-content:center;box-shadow:var(--shadow-sm)}\n'
   + '.capture-brand svg{width:17px;height:17px}\n'
   + '.capture-title{flex:1;min-width:0;margin:0;font-family:var(--serif);'
   + 'font-weight:700;font-size:16px;letter-spacing:.02em}\n'
   + '.capture-body{flex:1;min-height:0;overflow-y:auto;'
   + 'overscroll-behavior:contain;padding:12px 14px 16px}\n'
   + '.capture-tabs{display:flex;flex:none;margin:10px 12px 0;padding:4px;'
   + 'gap:4px;border:1px solid var(--hair);border-radius:999px;'
   + 'background:var(--surface2)}\n'
   + '.capture-tab{flex:1;min-height:40px;border:0;border-radius:999px;'
   + 'background:transparent;color:var(--ink2);font:inherit;font-size:12.5px;'
   + 'font-weight:600;cursor:pointer;transition:color .15s,background .15s}\n'
   + '.capture-tab.on{background:var(--surface);color:var(--ink);'
   + 'box-shadow:var(--shadow-sm)}\n'
   + '.capture-dash[data-tab=\'upload\'] .capture-pane-leaderboard'
   + '{display:none}\n'
   + '.capture-dash[data-tab=\'leaderboard\'] .capture-pane-upload'
   + '{display:none}\n'
   + '.capture-form{display:flex;flex-direction:column;gap:10px;'
   + 'margin-top:10px}\n'
   + '.capture-user{display:flex;align-items:center;gap:10px;padding:10px;'
   + 'border:1px solid var(--hair);border-radius:var(--r-md);'
   + 'background:var(--surface2)}\n'
   + '.capture-avatar{width:36px;height:36px;flex:none;border-radius:50%;'
   + 'background:var(--accent-soft);color:var(--accent-ink);display:flex;'
   + 'align-items:center;justify-content:center;font-family:var(--serif);'
   + 'font-weight:700;font-size:13px}\n'
   + '.capture-user-who{flex:1;min-width:0;display:flex;'
   + 'flex-direction:column}\n'
   + '.capture-user-who b{font-size:12.5px;color:var(--ink);'
   + 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n'
   + '.capture-user-who span{font-size:10.5px;color:var(--ink3);'
   + 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n'
   + '.capture-points-chip{flex:none;font-size:10.5px;font-weight:600;'
   + 'color:var(--accent-ink);background:var(--accent-soft);'
   + 'border-radius:999px;padding:4px 9px;white-space:nowrap}\n'
   + '.capture-chips{display:flex;flex-wrap:wrap;gap:8px}\n'
   + '.capture-chip{position:relative;display:inline-flex;align-items:center;'
   + 'gap:6px;min-height:44px;padding:8px 14px;border-radius:999px;'
   + 'border:1px solid var(--hair);background:var(--surface);'
   + 'color:var(--ink2);cursor:pointer;font-size:12.5px;'
   + 'transition:border-color .15s,background .15s,color .15s}\n'
   + '.capture-chip:hover{border-color:var(--hair-strong)}\n'
   + '.capture-chip.on{border-color:var(--accent);color:var(--ink);'
   + 'background:var(--accent-soft);font-weight:600}\n'
   + '.capture-chip input[type=radio]{position:absolute;opacity:0;'
   + 'width:1px;height:1px;pointer-events:none}\n'
   + '.capture-input{background:var(--surface);border:1px solid var(--hair);'
   + 'border-radius:var(--r-sm);color:var(--ink);font:inherit;font-size:13px;'
   + 'padding:10px 12px;min-height:44px;width:100%}\n'
   + '.capture-input:focus{outline:1px solid var(--accent)}\n'
   + '.capture-file{position:absolute;width:1px;height:1px;opacity:0;'
   + 'pointer-events:none}\n'
   + '.capture-drop{display:flex;flex-direction:column;align-items:center;'
   + 'gap:4px;text-align:center;padding:18px 12px;'
   + 'border:1px dashed var(--hair-strong);border-radius:var(--r-sm);'
   + 'background:var(--surface2);color:var(--ink3);cursor:pointer;'
   + 'transition:border-color .15s,color .15s}\n'
   + '.capture-drop:hover{border-color:var(--accent);color:var(--ink2)}\n'
   + '.capture-drop b{font-size:12.5px;color:var(--ink2)}\n'
   + '.capture-drop span{font-size:10.5px;max-width:34ch}\n'
   + '.capture-drop-ico{width:22px;height:22px;color:var(--accent)}\n'
   + '.capture-file-row{display:flex;align-items:center;gap:10px;'
   + 'padding:10px 12px;border:1px solid var(--hair);'
   + 'border-radius:var(--r-sm);background:var(--surface2)}\n'
   + '.capture-file-ico{width:30px;height:30px;flex:none;'
   + 'border-radius:var(--r-xs);background:var(--accent-soft);'
   + 'color:var(--accent-ink);display:flex;align-items:center;'
   + 'justify-content:center}\n'
   + '.capture-file-ico svg{width:15px;height:15px}\n'
   + '.capture-file-meta{flex:1;min-width:0;display:flex;'
   + 'flex-direction:column;text-align:left}\n'
   + '.capture-file-meta b{font-size:12px;color:var(--ink);'
   + 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n'
   + '.capture-file-meta span{font-size:10.5px;color:var(--ink3)}\n'
   + '.capture-file-row button{min-width:0;padding:6px 10px}\n'
   + '.capture-field{display:flex;flex-direction:column;gap:5px;'
   + 'font-size:11px;font-weight:600;letter-spacing:.08em;color:var(--ink3)}\n'
   + '.form-error{color:var(--red);font-size:12.5px;font-weight:600}\n'
   + '.capture-acc{display:flex;flex-direction:column;gap:8px;margin:8px 0}\n'
   + '.capture-acc-item{border:1px solid var(--hair);'
   + 'border-radius:var(--r-md);background:var(--surface);overflow:hidden}\n'
   + '.capture-acc-item.on{border-color:var(--hair-strong)}\n'
   + '.capture-acc-head{display:flex;align-items:center;gap:10px;width:100%;'
   + 'min-height:52px;padding:10px 12px;border:0;background:transparent;'
   + 'color:var(--ink);cursor:pointer;text-align:left;font-weight:600}\n'
   + '.capture-acc-glyph{width:32px;height:32px;flex:none;'
   + 'border-radius:var(--r-sm);background:var(--surface2);display:flex;'
   + 'align-items:center;justify-content:center}\n'
   + '.capture-acc-glyph svg{width:16px;height:16px}\n'
   + '.capture-acc-glyph.g0{color:var(--accent)}\n'
   + '.capture-acc-glyph.g1{color:var(--green)}\n'
   + '.capture-acc-glyph.g2{color:var(--today)}\n'
   + '.capture-acc-glyph.g3{color:var(--amber)}\n'
   + '.capture-acc-title{flex:1;min-width:0;font-size:12.5px}\n'
   + '.capture-acc-chev{flex:none;width:16px;height:16px;color:var(--ink3);'
   + 'transition:transform .25s}\n'
   + '.capture-acc-item.on .capture-acc-chev{transform:rotate(180deg)}\n'
   + '.capture-acc-body{display:grid;grid-template-rows:0fr;'
   + 'transition:grid-template-rows .3s ease}\n'
   + '.capture-acc-item.on .capture-acc-body{grid-template-rows:1fr}\n'
   + '.capture-acc-inner{overflow:hidden;min-height:0}\n'
   + '.capture-acc-content{padding:2px 12px 12px;'
   + 'border-top:1px solid var(--hair)}\n'
   + '.capture-acc-ask{margin:10px 0;font-size:11.5px;color:var(--ink2);'
   + 'line-height:1.45}\n'
   + '.capture-acc-tiles{display:grid;grid-template-columns:1fr 1fr;gap:8px}\n'
   + '.capture-acc-tile{padding:8px 9px;border:1px solid var(--hair);'
   + 'border-radius:var(--r-sm);background:var(--surface2)}\n'
   + '.capture-acc-tile b{display:block;font-size:9px;letter-spacing:.08em;'
   + 'text-transform:uppercase;color:var(--accent-ink);margin-bottom:3px}\n'
   + '.capture-acc-tile span{font-size:10.5px;color:var(--ink3);'
   + 'line-height:1.4}\n'
   + '.capture-lb-glyph{width:28px;height:28px;flex:none;'
   + 'border-radius:var(--r-xs);background:var(--surface2);'
   + 'color:var(--amber);display:flex;align-items:center;'
   + 'justify-content:center}\n'
   + '.capture-lb-glyph svg{width:14px;height:14px}\n'
   + '.capture-lb{display:flex;flex-direction:column;gap:2px;margin-top:8px}\n'
   + '.capture-lb-row{display:flex;align-items:center;gap:10px;'
   + 'padding:8px 10px;border:1px solid transparent;'
   + 'border-radius:var(--r-sm)}\n'
   + '.capture-lb-row b{flex:1;min-width:0;font-size:12.5px;'
   + 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n'
   + '.capture-lb-row .capture-avatar{width:28px;height:28px;font-size:11px}\n'
   + '.capture-lb-row .capture-rank{width:30px;flex:none}\n'
   + '.capture-rank{font-family:var(--mono);font-size:12px;'
   + 'color:var(--ink3);width:38px;flex:none}\n'
   + '.capture-lb-top{border-color:var(--hair);background:var(--surface2)}\n'
   + '.capture-lb-top .capture-rank{color:var(--amber);font-weight:700}\n'
   + '.capture-lb button{margin-top:8px;align-self:flex-start}\n'
   + '.capture-veil{position:absolute;inset:0;z-index:40;'
   + 'background:var(--veil);display:flex;align-items:flex-end}\n'
   + '.capture-sheet{position:relative;width:100%;background:var(--surface);'
   + 'border-top:1px solid var(--hair);'
   + 'border-radius:var(--r-lg) var(--r-lg) 0 0;padding:18px 16px 14px;'
   + 'box-shadow:var(--shadow-lg);display:flex;flex-direction:column;'
   + 'align-items:center;gap:10px;text-align:center}\n'
   + '.capture-sheet-x{position:absolute;top:10px;right:10px;min-width:0;'
   + 'padding:6px;border:0;background:transparent;color:var(--ink3);'
   + 'cursor:pointer}\n'
   + '.capture-sheet-x svg{width:16px;height:16px}\n'
   + '.capture-sheet-glyph{width:44px;height:44px;border-radius:var(--r-md);'
   + 'background:var(--accent-soft);color:var(--accent-ink);display:flex;'
   + 'align-items:center;justify-content:center}\n'
   + '.capture-sheet-glyph svg{width:20px;height:20px}\n'
   + '.capture-sheet-title{margin:2px 0;font-family:var(--serif);'
   + 'font-weight:700;font-size:16px;color:var(--ink)}\n'
   + '.capture-sheet .hint{margin:0}\n'
   + '.capture-sheet .gbtn{margin-top:4px}\n'
   + '.capture-sheet-note{margin:0;font-size:10.5px;color:var(--ink3)}\n'
   /* competition-rules popup: a header-bar text link right of the
    * CAPTURE heading opens the verbatim rules copy over the dash —
    * centered dialog, only the body scrolls; token-only per the theme
    * contract. */
   + '/* capture rules popup */\n'
   + '.capture-rules-link{flex:none;min-height:32px;padding:0 6px;'
   + 'border:0;background:transparent;color:var(--accent-ink);'
   + 'font:inherit;font-size:12px;font-weight:600;cursor:pointer;'
   + 'text-decoration:underline;text-underline-offset:3px}\n'
   + '.capture-rules-link:hover{color:var(--accent)}\n'
   + '.capture-rules-veil{position:absolute;inset:0;z-index:50;'
   + 'background:var(--veil);display:flex;align-items:center;'
   + 'justify-content:center;padding:14px}\n'
   + '.capture-rules-pop{width:min(460px,100%);max-height:100%;'
   + 'background:var(--surface);border:1px solid var(--hair);'
   + 'border-radius:var(--r-lg);box-shadow:var(--shadow-lg);display:flex;'
   + 'flex-direction:column;overflow:hidden}\n'
   + '.capture-rules-head{flex:none;display:flex;align-items:center;'
   + 'gap:10px;padding:12px 14px;border-bottom:1px solid var(--hair)}\n'
   + '.capture-rules-title{flex:1;min-width:0;font-family:var(--serif);'
   + 'font-weight:700;font-size:13px;color:var(--ink)}\n'
   + '.capture-rules-x{flex:none;width:32px;height:32px;display:flex;'
   + 'align-items:center;justify-content:center;border:0;'
   + 'background:transparent;color:var(--ink3);cursor:pointer}\n'
   + '.capture-rules-x svg{width:16px;height:16px}\n'
   + '.capture-rules-body{flex:1;min-height:0;overflow-y:auto;'
   + 'overscroll-behavior:contain;padding:4px 16px 16px}\n'
   + '.capture-rules-h{margin:14px 0 4px;font-size:12.5px;font-weight:700;'
   + 'color:var(--ink)}\n'
   + '.capture-rules-p{margin:6px 0;font-size:12px;line-height:1.55;'
   + 'color:var(--ink2)}\n'
   + '.capture-rules-p strong{color:var(--ink);font-weight:700}\n'
   + '.capture-rules-ul{margin:6px 0;padding-left:18px}\n'
   + '.capture-rules-ul li{margin:5px 0;font-size:12px;line-height:1.55;'
   + 'color:var(--ink2)}\n'
   + '.capture-rules-ul li strong{color:var(--ink);font-weight:700}\n'
   /* upload success takeover: the accepted upload swaps the whole body
    * for the success moment, then auto-advances to the Leaderboard tab */
   + '/* upload success takeover */\n'
   + '.capture-success{min-height:280px;display:flex;flex-direction:column;'
   + 'align-items:center;justify-content:center;gap:8px;text-align:center}\n'
   + '.capture-success-glyph{width:56px;height:56px;flex:none;'
   + 'border-radius:50%;background:var(--accent-soft);'
   + 'color:var(--accent-ink);display:flex;align-items:center;'
   + 'justify-content:center}\n'
   + '.capture-success-glyph svg{width:26px;height:26px}\n'
   + '.capture-success-title{font-family:var(--serif);font-weight:700;'
   + 'font-size:17px;color:var(--ink)}\n'
   + '.capture-success-sub{font-size:12px;color:var(--ink3);'
   + 'max-width:32ch}\n'
   /* Capture mobile takeover (house <=900px breakpoint, same as the
    * compact topbar + SimPanel sheet): the capture page takes over the
    * full screen — the topbar steps aside via the TopBar marker and the
    * dash fills the phone. The Upload | Leaderboard tabs + data-tab pane
    * swap are UNIVERSAL (styled in the capture block above, every width);
    * this block only keeps the phone takeover tweaks. */
   + '@media (max-width:900px){\n'
   + '.capture-dash{width:100%;max-height:100%;height:100%;'
   + 'border-radius:0;border-left:0;border-right:0}\n'
   + '.topbar-under-capture{display:none}\n'
   + '.capture-body{padding:10px 12px 14px}\n'
   + '.capture-acc-tiles{grid-template-columns:1fr}}\n';

const __simoStyle = document.createElement('style');
__simoStyle.textContent = BALAGERE_CSS_STYLE + EXTRA_CSS;
document.head.appendChild(__simoStyle);

ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(IntroShell, null, React.createElement(App)));
